### ISSUE TITLE
Mojave 10.14.5: imported username/password doesn't get synced into iCloud

### ISSUE THREAD

**Issue by mrjayviper** [nntarasov/csv2keychain#9]
When I ran the csv2keychain against the exported Chrome password, the passwords were imported into my Keychain BUT they were imported inside the "login" keychain.

Results:
1. I went to Safari => Preferences => Passwords and none of the imported passwords showed up there
2. none of the imported passwords were synced to my iOS devices

As a test, I manually entered the username and password for a stackexchange.com. I went back to Keychain Access and the stackexchange.com username/password got saved into "iCloud" keychain.

Results:
1. stackexchange details showed up inside Safari => Preferences => Passwords
2. username/password was synced to my iOS devices

**Comment by nntarasov** [comment]
Thank you for the feedback. The issue is known - here are some details - https://github.com/nntarasov/csv2keychain/issues/5#issuecomment-479961645

**Comment by tyrann0us** [comment]
Hi @nntarasov, is there an update for the missing iCloud sync? I think more and more people are using iCloud, so it would be really great if there was a way to specify the `iCloud` keychain when running the script.

Of course, we would have to figure out how to make `security add-internet-password` work with the iCloud keychain first.

Thanks!

**Comment by nntarasov** [comment]
Since Catalina update 10.15.4 there is a feature in macOS that allows import chrome passwords into iCloud keychain :)

https://support.apple.com/kb/DL2036?locale=en_US

> Safari
• Option to import Chrome passwords into your iCloud Keychain for easy AutoFill of your passwords in Safari and across all your devices


> Of course, we would have to figure out how to make security add-internet-password work with the iCloud keychain first.

It would be great to have such ability, that means we can add custom credentials into keychain - it can be useful for password manager programs. I've tried to figure it out earlier - there was some complicated process not dependent on `security` utility

**Comment by tyrann0us** [comment]
Thanks! Wasn't aware of this feature. Here's the official documentation: https://support.apple.com/guide/safari/import-bookmarks-history-and-passwords-ibrw1015/mac
And according to that document, the import feature has been available since macOS High Sierra (`v10.13`). So I guess that for most users, this would be the preferred way to import their Chrome passwords to the (iCloud) keychain, instead using this script.

Would it make sense to mention the official feature in the `README.md`? This would have save me quite some time. 😄
